version: 0.0
os: linux
files:
  - source: /slow-hello-world.js
    destination: /var/node
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
 ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300
      runas: root